// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id, amount, currency, category, description, raw_input
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, amount, currency, category, description, raw_input, created_at
`

type CreateTransactionParams struct {
	UserID      uuid.UUID       `json:"user_id"`
	Amount      decimal.Decimal `json:"amount"`
	Currency    string          `json:"currency"`
	Category    pgtype.Text     `json:"category"`
	Description pgtype.Text     `json:"description"`
	RawInput    pgtype.Text     `json:"raw_input"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Currency,
		arg.Category,
		arg.Description,
		arg.RawInput,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Category,
		&i.Description,
		&i.RawInput,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, email, accepted_terms_version, accepted_terms_at, allow_data_analysis
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, email, accepted_terms_version, accepted_terms_at, allow_data_analysis, created_at
`

type CreateUserParams struct {
	ID                   uuid.UUID   `json:"id"`
	Email                string      `json:"email"`
	AcceptedTermsVersion pgtype.Text `json:"accepted_terms_version"`
	AcceptedTermsAt      time.Time   `json:"accepted_terms_at"`
	AllowDataAnalysis    pgtype.Bool `json:"allow_data_analysis"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.AcceptedTermsVersion,
		arg.AcceptedTermsAt,
		arg.AllowDataAnalysis,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.AcceptedTermsVersion,
		&i.AcceptedTermsAt,
		&i.AllowDataAnalysis,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one

SELECT id, email, accepted_terms_version, accepted_terms_at, allow_data_analysis, created_at FROM users
WHERE id = $1 LIMIT 1
`

// Copyright (c) 2026 dilocash
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.
func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.AcceptedTermsVersion,
		&i.AcceptedTermsAt,
		&i.AllowDataAnalysis,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionsByUserId = `-- name: ListTransactionsByUserId :many
SELECT id, user_id, amount, currency, category, description, raw_input, created_at FROM transactions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByUserIdParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListTransactionsByUserId(ctx context.Context, arg ListTransactionsByUserIdParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.Description,
			&i.RawInput,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
