// Copyright (c) 2026 dilocash
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.

package sync

import (
	"context"
	"errors"
	"log/slog"

	"connectrpc.com/connect"
	mappers "github.com/dilocash/dilocash-oss/apps/api/internal/generated/mappers"
	v1 "github.com/dilocash/dilocash-oss/apps/api/internal/generated/transport/dilocash/v1"
	"github.com/dilocash/dilocash-oss/apps/api/internal/usecase"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// SyncServer implements the interface generated by gRPC/Connect
type SyncServer struct {
	syncPullUsecase *usecase.SyncPullUsecase
	syncPushUsecase *usecase.SyncPushUsecase
}

func NewSyncServer(syncPullUsecase *usecase.SyncPullUsecase, syncPushUsecase *usecase.SyncPushUsecase) *SyncServer {
	return &SyncServer{
		syncPullUsecase: syncPullUsecase,
		syncPushUsecase: syncPushUsecase,
	}
}

func (s *SyncServer) PullChanges(
	ctx context.Context,
	req *v1.PullChangesRequest,
) (*v1.PullChangesResponse, error) {
	timestamp := timestamppb.Now() // keep timestamp before running any query
	converter := &mappers.ConverterImpl{}
	profileId := ctx.Value("user_id").(string)
	lastPulledAt := req.GetLastPulledAt()

	syncChanges, err := s.syncPullUsecase.Execute(ctx, profileId, lastPulledAt.AsTime())
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, errors.New("failed to pull changes"))
	}
	serviceCommands := []*v1.Command{}
	serviceCommandsUpdated := []*v1.Command{}
	serviceCommandsDeleted := []string{}
	serviceIntents := []*v1.Intent{}
	serviceIntentsUpdated := []*v1.Intent{}
	serviceIntentsDeleted := []string{}
	serviceTransactions := []*v1.Transaction{}
	serviceTransactionsUpdated := []*v1.Transaction{}
	serviceTransactionsDeleted := []string{}

	for _, command := range syncChanges.Commands.Created {
		serviceCommands = append(serviceCommands, converter.ToTransportCommand(command))
	}
	for _, command := range syncChanges.Commands.Updated {
		serviceCommandsUpdated = append(serviceCommandsUpdated, converter.ToTransportCommand(command))
	}
	for _, command := range syncChanges.Commands.Deleted {
		serviceCommandsDeleted = append(serviceCommandsDeleted, command.String())
	}
	for _, intent := range syncChanges.Intents.Created {
		serviceIntents = append(serviceIntents, converter.ToTransportIntent(intent))
	}
	for _, intent := range syncChanges.Intents.Updated {
		serviceIntentsUpdated = append(serviceIntentsUpdated, converter.ToTransportIntent(intent))
	}
	for _, intent := range syncChanges.Intents.Deleted {
		serviceIntentsDeleted = append(serviceIntentsDeleted, intent.String())
	}
	for _, transaction := range syncChanges.Transactions.Created {
		serviceTransactions = append(serviceTransactions, converter.ToTransportTransaction(transaction))
	}
	for _, transaction := range syncChanges.Transactions.Updated {
		serviceTransactionsUpdated = append(serviceTransactionsUpdated, converter.ToTransportTransaction(transaction))
	}
	for _, transaction := range syncChanges.Transactions.Deleted {
		serviceTransactionsDeleted = append(serviceTransactionsDeleted, transaction.String())
	}

	return buildPullChangesResponse(timestamp, &v1.CommandsList{
		Created: serviceCommands,
		Updated: serviceCommandsUpdated,
		Deleted: serviceCommandsDeleted,
	}, &v1.IntentsList{
		Created: serviceIntents,
		Updated: serviceIntentsUpdated,
		Deleted: serviceIntentsDeleted,
	}, &v1.TransactionsList{
		Created: serviceTransactions,
		Updated: serviceTransactionsUpdated,
		Deleted: serviceTransactionsDeleted,
	})
}

func (s *SyncServer) PushChanges(
	ctx context.Context,
	req *v1.PushChangesRequest,
) (*v1.PushChangesResponse, error) {
	profileId := ctx.Value("user_id").(string)
	lastPulledAt := req.GetLastPulledAt()
	slog.Info("pushing changes", "profileId", profileId, "changes", req.GetChanges(), "lastPulledAt", lastPulledAt.AsTime())

	s.syncPushUsecase.Execute(ctx, profileId, lastPulledAt.AsTime())

	slog.Info("changes pushed successfully", "profileId", profileId)

	return &v1.PushChangesResponse{
		Ok:          true,
		ConflictIds: []string{},
	}, nil
}

func buildPullChangesResponse(timestamp *timestamppb.Timestamp, commandsList *v1.CommandsList, intentsList *v1.IntentsList, transactionsList *v1.TransactionsList) (*v1.PullChangesResponse, error) {
	return &v1.PullChangesResponse{
		Timestamp: timestamp,
		Changes: &v1.Changes{
			Commands:     commandsList,
			Intents:      intentsList,
			Transactions: transactionsList,
		},
	}, nil
}
