// Copyright (c) 2026 dilocash
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.

package sync

import (
	"context"
	"errors"
	"log/slog"
	"time"

	"connectrpc.com/connect"
	"github.com/dilocash/dilocash-oss/apps/api/internal/domain"
	mappers "github.com/dilocash/dilocash-oss/apps/api/internal/generated/mappers"
	v1 "github.com/dilocash/dilocash-oss/apps/api/internal/generated/transport/dilocash/v1"
	"github.com/google/uuid"
	"google.golang.org/protobuf/types/known/timestamppb"
)

type SyncPullUsecaseExecutor interface {
	Execute(ctx context.Context, profileId string, lastPulledAt time.Time) (*domain.SyncChanges, error)
}

type SyncPushUsecaseExecutor interface {
	Execute(ctx context.Context, profileId string, lastPulledAt time.Time, syncChanges *domain.SyncChanges) error
}

// SyncServer implements the interface generated by gRPC/Connect
type SyncServer struct {
	syncPullUsecase SyncPullUsecaseExecutor
	syncPushUsecase SyncPushUsecaseExecutor
}

func NewSyncServer(syncPullUsecase SyncPullUsecaseExecutor, syncPushUsecase SyncPushUsecaseExecutor) *SyncServer {
	return &SyncServer{
		syncPullUsecase: syncPullUsecase,
		syncPushUsecase: syncPushUsecase,
	}
}

func (s *SyncServer) PullChanges(
	ctx context.Context,
	req *v1.PullChangesRequest,
) (*v1.PullChangesResponse, error) {
	timestamp := timestamppb.Now() // keep timestamp before running any query
	converter := &mappers.ConverterImpl{}
	profileId := ctx.Value("user_id").(string)
	lastPulledAt := req.GetLastPulledAt()

	syncChanges, err := s.syncPullUsecase.Execute(ctx, profileId, lastPulledAt.AsTime())
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, errors.New("failed to pull changes"))
	}
	serviceCommands := []*v1.Command{}
	serviceCommandsUpdated := []*v1.Command{}
	serviceCommandsDeleted := []string{}
	serviceIntents := []*v1.Intent{}
	serviceIntentsUpdated := []*v1.Intent{}
	serviceIntentsDeleted := []string{}
	serviceTransactions := []*v1.Transaction{}
	serviceTransactionsUpdated := []*v1.Transaction{}
	serviceTransactionsDeleted := []string{}

	for _, command := range syncChanges.Commands.Created {
		serviceCommands = append(serviceCommands, converter.ToTransportCommand(command))
	}
	for _, command := range syncChanges.Commands.Updated {
		serviceCommandsUpdated = append(serviceCommandsUpdated, converter.ToTransportCommand(command))
	}
	for _, command := range syncChanges.Commands.Deleted {
		serviceCommandsDeleted = append(serviceCommandsDeleted, command.String())
	}
	for _, intent := range syncChanges.Intents.Created {
		serviceIntents = append(serviceIntents, converter.ToTransportIntent(intent))
	}
	for _, intent := range syncChanges.Intents.Updated {
		serviceIntentsUpdated = append(serviceIntentsUpdated, converter.ToTransportIntent(intent))
	}
	for _, intent := range syncChanges.Intents.Deleted {
		serviceIntentsDeleted = append(serviceIntentsDeleted, intent.String())
	}
	for _, transaction := range syncChanges.Transactions.Created {
		serviceTransactions = append(serviceTransactions, converter.ToTransportTransaction(transaction))
	}
	for _, transaction := range syncChanges.Transactions.Updated {
		serviceTransactionsUpdated = append(serviceTransactionsUpdated, converter.ToTransportTransaction(transaction))
	}
	for _, transaction := range syncChanges.Transactions.Deleted {
		serviceTransactionsDeleted = append(serviceTransactionsDeleted, transaction.String())
	}

	return buildPullChangesResponse(timestamp, &v1.CommandsList{
		Created: serviceCommands,
		Updated: serviceCommandsUpdated,
		Deleted: serviceCommandsDeleted,
	}, &v1.IntentsList{
		Created: serviceIntents,
		Updated: serviceIntentsUpdated,
		Deleted: serviceIntentsDeleted,
	}, &v1.TransactionsList{
		Created: serviceTransactions,
		Updated: serviceTransactionsUpdated,
		Deleted: serviceTransactionsDeleted,
	})
}

func (s *SyncServer) PushChanges(
	ctx context.Context,
	req *v1.PushChangesRequest,
) (*v1.PushChangesResponse, error) {
	profileId := ctx.Value("user_id").(string)
	lastPulledAt := req.GetLastPulledAt()
	converter := &mappers.ConverterImpl{}
	slog.Info("pushing changes", "profileId", profileId, "changes", req.GetChanges(), "lastPulledAt", lastPulledAt.AsTime())

	commands := domain.SyncPayload[*domain.Command]{
		Created: []*domain.Command{},
		Updated: []*domain.Command{},
		Deleted: []uuid.UUID{},
	}
	for _, command := range req.GetChanges().GetCommands().GetCreated() {
		commands.Created = append(commands.Created, converter.CommandFromTransportToDomain(command))
	}
	for _, command := range req.GetChanges().GetCommands().GetUpdated() {
		commands.Updated = append(commands.Updated, converter.CommandFromTransportToDomain(command))
	}
	for _, command := range req.GetChanges().GetCommands().GetDeleted() {
		commands.Deleted = append(commands.Deleted, uuid.MustParse(command))
	}

	intents := domain.SyncPayload[*domain.Intent]{
		Created: []*domain.Intent{},
		Updated: []*domain.Intent{},
		Deleted: []uuid.UUID{},
	}
	for _, i := range req.GetChanges().GetIntents().GetCreated() {
		intents.Created = append(intents.Created, converter.IntentFromTransportToDomain(i))
	}
	for _, i := range req.GetChanges().GetIntents().GetUpdated() {
		intents.Updated = append(intents.Updated, converter.IntentFromTransportToDomain(i))
	}
	for _, i := range req.GetChanges().GetIntents().GetDeleted() {
		intents.Deleted = append(intents.Deleted, uuid.MustParse(i))
	}

	transactions := domain.SyncPayload[*domain.Transaction]{
		Created: []*domain.Transaction{},
		Updated: []*domain.Transaction{},
		Deleted: []uuid.UUID{},
	}
	for _, t := range req.GetChanges().GetTransactions().GetCreated() {
		transactions.Created = append(transactions.Created, converter.TransactionFromTransportToDomain(t))
	}
	for _, t := range req.GetChanges().GetTransactions().GetUpdated() {
		transactions.Updated = append(transactions.Updated, converter.TransactionFromTransportToDomain(t))
	}
	for _, t := range req.GetChanges().GetTransactions().GetDeleted() {
		transactions.Deleted = append(transactions.Deleted, uuid.MustParse(t))
	}

	syncChanges := domain.SyncChanges{
		Commands:     commands,
		Intents:      intents,
		Transactions: transactions,
	}

	err := s.syncPushUsecase.Execute(ctx, profileId, lastPulledAt.AsTime(), &syncChanges)

	if err != nil {
		return nil, err
	}
	slog.Info("changes pushed successfully", "profileId", profileId)

	return &v1.PushChangesResponse{
		Ok:          true,
		ConflictIds: []string{},
	}, nil
}

func buildPullChangesResponse(timestamp *timestamppb.Timestamp, commandsList *v1.CommandsList, intentsList *v1.IntentsList, transactionsList *v1.TransactionsList) (*v1.PullChangesResponse, error) {
	return &v1.PullChangesResponse{
		Timestamp: timestamp,
		Changes: &v1.Changes{
			Commands:     commandsList,
			Intents:      intentsList,
			Transactions: transactionsList,
		},
	}, nil
}
